services:
  gitlab-web:
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab-web
    hostname: gitlab-web
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'http://localhost:4567'
        registry['enable'] = true
        unicorn['socket'] = '/opt/gitlab/var/unicorn/gitlab.socket'        
    ports:
    - '8080:80'
    - '443:443'
    - '3000:3000'
    - '2222:22'
    - '4567:4567'
    - '9090:9090'
    volumes:
    - './config:/etc/gitlab'
    - './logs:/var/log/gitlab'
    - './data:/var/opt/gitlab'
    networks:
    - gitlab-network

  gitlab-runner1:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    volumes:
    - './runner1_config:/etc/gitlab-runner:Z'
    - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
    - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network
